import importlib.util
import os
from pathlib import Path
import unittest
from unittest.mock import Mock, AsyncMock, patch
import asyncio

os.environ.setdefault('TELEGRAM_BOT_TOKEN', 'test-only')
ROOT = Path(__file__).resolve().parents[1]
spec = importlib.util.spec_from_file_location('link_summary', ROOT / 'pharma-news/scripts/bot_link_summary.py')
bot = importlib.util.module_from_spec(spec)
spec.loader.exec_module(bot)
URL = 'https://www.businesspost.co.kr/BP?command=article_view&num=447362'
BODY = 'The company announced a supply contract with its overseas customer. ' * 5


def response(text, error=None):
    res = Mock(text=text)
    res.raise_for_status.side_effect = error
    return res


class LinkSummaryTests(unittest.TestCase):
    def test_http_403_uses_same_article_mobile_version(self):
        blocked = response('CloudFront 403', bot.requests.HTTPError())
        mobile = response('<meta property="og:title" content="Article title"><div class="conPost">' + BODY + '</div>')
        with patch.object(bot.requests, 'get', side_effect=[blocked, mobile]) as get:
            title, body = bot.fetch_article(URL)
        self.assertEqual(title, 'Article title')
        self.assertIn('supply contract', body)
        self.assertIn('mobile_view&num=447362', get.call_args_list[1].args[0])

    def test_error_page_with_success_status_is_rejected(self):
        page = '<title>ERROR: The request could not be satisfied</title><article>403 ERROR The request could not be satisfied. Generated by CloudFront</article>'
        with patch.object(bot.requests, 'get', return_value=response(page)):
            with self.assertRaises(bot.ArticleUnavailable):
                bot.fetch_article(URL)

    def test_navigation_is_not_used_as_article_body(self):
        with patch.object(bot.requests, 'get', return_value=response('<title>News</title><nav>' + BODY + '</nav>')):
            with self.assertRaises(bot.ArticleUnavailable):
                bot.fetch_article('https://example.com')

    def test_error_never_reaches_model_or_raw_error_reply(self):
        status = Mock(edit_text=AsyncMock())
        message = Mock(text=URL, reply_text=AsyncMock(return_value=status))
        with patch.object(bot, 'ANTHROPIC_API_KEY', 'test-only'), patch.object(bot, 'fetch_article', side_effect=bot.ArticleUnavailable()), patch.object(bot, 'summarize') as summarize:
            asyncio.run(bot.on_message(Mock(message=message), Mock()))
        summarize.assert_not_called()
        reply = status.edit_text.call_args.args[0]
        self.assertNotIn('CloudFront', reply)
        self.assertNotIn('403', reply)
        self.assertIn('447362', reply)

    def test_healthy_body_is_used_without_mobile_request(self):
        page = '<meta property="og:title" content="Actual title"><div id="article-body-content">' + BODY + '</div>'
        with patch.object(bot.requests, 'get', return_value=response(page)) as get:
            self.assertEqual(bot.fetch_article(URL)[0], 'Actual title')
            get.assert_called_once()

if __name__ == '__main__':
    unittest.main()
